<?php
  $this->load->view('templates/01_head.php');
  $this->load->view('templates/02_header.php');
  $this->load->view('templates/03_headerbar.php');
  $this->load->view('modals/logout');
  $this->load->view('modals/pegawai');
  $this->load->view('modals/password');
  $this->load->view('templates/04_sidebar.php');
  $this->load->view('pages/notif.php');
 ?>
