<?php
$this->load->view('templates/01_head.php');
$this->load->view('templates/02_header.php');
$this->load->view('templates/03_headerbar.php');
$this->load->view('templates/04_sidebar.php');
$this->load->view('templates/05_content.php');
$this->load->view('templates/06_footer.php');
$this->load->view('templates/07_controlbar.php');
$this->load->view('templates/08_javascript.php');
?>
